# Generated by Django 4.1 on 2024-06-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('短信类别', models.SmallIntegerField()),
                ('短信内容', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='phone_number',
            fields=[
                ('电话号码', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('电话类型', models.CharField(default=None, max_length=10, null=True)),
                ('标记次数', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='诈骗类型说明',
            fields=[
                ('诈骗类型id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('诈骗类型', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='website',
            fields=[
                ('网站域名', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('诈骗类型', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SE.诈骗类型说明')),
            ],
        ),
    ]
